# Generated by Django 2.2.27 on 2023-03-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_auto_20230322_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
