# Generated by Django 2.2.27 on 2023-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_students_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
