# Generated by Django 2.2.27 on 2023-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_auto_20230322_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=1, max_length=10),
        ),
    ]
